### ISSUE TITLE
Flags API Discussion

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#105]
There are a few considerations for the new `ppb.flags` module.

The docstring makes it very clear what the purpose is:

Flags should be singletons, and compared with `is`, just like a `None` comparison.

Writing new flags can take two, primary, forms:

1) Write a constant with a plain `object`: ` MY_FLAG = object()`
2) Subclass a stub class that works similarly to `None`: `class MyFlag(Flag): pass`

The nicest thing about the second form is that it makes docstrings available for calls to `help`:

```python
class MyFlag(Flag):
    """Signifies a thing that I want to watch for."""
```

The downfall, though, is they're types, and types, typically, are callable.

```python
flag = MyFlag()
```

The current implementation allows you to do this, but just returns the type itself as `__new__` and ignores the `__init__`.

@astronouth7303 suggested that this be disallowed and raise an error. I'm not against this, but I'd like the conversation to be public. So is preventing calling `Flags` a valuable feature?

**Comment by astronouth7303** [comment]
In the strictest of purity, they should have a class and a value. (Like `None`/`NoneType` and `Ellipsis`/`<class 'ellipsis'>`.) I'm leaning towards "Practicality beats Purity" in this case, though, because I don't see what value it brings.

So, using types as singletons:
* They're not constructable (having more of them doesn't make sense), so calling the factory (the class itself) is a programmer error. Going with the attitudes of PPB, programmer errors should be caught and raise explicit errors.
* I generally consider having docstrings to be of great importance, going to great lengths to enable them. (Aside: I should write a snippet to universally add a docstring to an instance.)

Although you can get a similar effect as `NoneType` by making `Flag` a metaclass:

```
class Flag(type):
    """Inherit from Flag to make a simple class flag."""
    def __call__(self, *args, **kwargs):
        """Do not use."""
        raise TypeError("Not constructable")
    def __eq__(self, other):
        return self is other
    def __repr__(self):
        return self.__name__


class DoNotRender(metaclass=Flag):
    """Inform the renderer to ignore this object."""
```

Then `type(DoNotRender)` is `Flag`, and it kinda looks more like a value.

**Comment by astronouth7303** [comment]
Counter-argument:

```
>>> type(...)() is ...
True
>>> type(None)() is None
True
```

**Comment by pathunstrom** [comment]
Sitting on this, I really like the metaclass version, though I don't like overriding `__eq__` since that breaks the "compare like None" bit. I want users to compare with `is` for flags.

And the counterargument is valid, I wonder if we can find a safe way to override the type's `__call__` to get a similar effect without the metaclass?

Time to experiment!

**Comment by astronouth7303** [comment]
Without the metaclass, override `__new__()` as you did originally.

Hm. With the metaclass version you might also be able to return an instance at class creation time.

**Comment by astronouth7303** [comment]
#164 handles this well. Flags are objects with individual docstrings, singletons are handled correctly, allows for subclassing, and keeps the syntax very clean.

**Comment by astronouth7303** [comment]
Closing this, as I think the current flags system is Pretty Good?
