### ISSUE TITLE
Magical Field System

### ISSUE THREAD

**Issue by astronouth7303** [ppb/pursuedpybear#234]
Need a way to do fields such that:

* Allow conversions/castings when set
* Allow virtual/generated fields
* Allows values to be set in the class definition of a subclass

**Comment by astronouth7303** [comment]
I'm currently thinking a field system, where a class may declare a field (property descriptor-looking thing? annotation? class decorator?), a metaclass aggregates the fields into a `__fields__` (from parent classes and the current class definition), and a class that has an `__init__` to set and copy from class and `__setattr__`/`__getattribute__` to dispatch conversion/computation.

The metaclass insures the MRO is followed, and the base class does the actual work.

**Comment by astronouth7303** [comment]
So, this is basically departing from the standard python idea of properties/attributes/etc.

Like, afaik nothing in the Python ecosystem behaves like this.

**Comment by jamesBrosnahan** [comment]
@astronouth7303 When you say that you need a way to do something [Need a way to do fields such that] but, do not include the use case; it becomes nearly impossible to know if another [more Pythonic] method could be used.
I think that implementing something different from the standard python will harm the projects goal of being education friendly since it will add an unintuitive footnote to any documentation about the system.
I believe that some Python ORM modules [Django models] create fields dynamically as row objects are generated but, they have the benefit of having a model class to template against.

P.S. events.py, buttons.py, and keycodes.py can benefit a lot from having identical methods consolidated with decorators  and keycode classes generated from a dictionary of keycodes  #173 
I am not sure how to file an issue that would cover both [check keyboard and mouse types, load a dictionary matching a supported layout and use setattr to generate the classes] but, I think they are relevant to this issue.

**Comment by astronouth7303** [comment]
The use case is that some kinds of properties (rotation, facing, left, top, right, bottom, position, ...) have code associated with them. The exact nature of this code varies from simple castings and value normalization to fully virtual properties.

Now, we've gotten exceedingly positive feedback that setting values on the class level works, works with subclassing, and works with multiple inheritance, so we very much do not want to disable that.

However, this may cause problems:

```
class MySprite(BaseSprite):
    position = (4, 2)
```

because it's never coerced into a `Vector`, and something elsewhere might expect to be able to use it as a vector (eg, rotation or reflection).

In addition, other properties (eg, facing) just don't work on the class level. If you set them on a class definition, they'll be ignored or mess other things up.

I'm currently leaning towards "Use lots of magic to make it look almost like python and be exceedingly usable" over "Use very little magic and be less usable".

So, the problem is that we have different tiers of properties with different usability. I want to normalize this so that all of them can be used in all cases and they'll work as a naive reading would expect.

**Comment by jamesBrosnahan** [comment]
What do you think about using __call__ to make properties callable classes that contain their specific logic?

**Comment by astronouth7303** [comment]
Callables don't support the semantics we need. We need values attached to instances that are gettable and settable. This describes properties (`spam.egg`) and subscription (`spam['egg']`). Given that the schema of the data will be mostly influenced by the class tree, properties are more closely aligned.

The way to make callables work is to do something like jQuery or use Java-ish getters and setters. I'm just going to veto these out of hand.

**Comment by jamesBrosnahan** [comment]
OK, thanks; I thought that doing something like getters and setters would be more Pythonic if they are abstracted with \_\_call\_\_.

**Comment by astronouth7303** [comment]
`__call__` is just a method to make something callable. It doesn't change the fact that the user sees `sprite.set_facing(spam)` and getters/setters are one of the least idiomatic things you can do.

**Comment by astronouth7303** [comment]
Attempted this, deemed too magical
