### ISSUE TITLE
Migrate away from PyGame

### ISSUE THREAD

**Issue by astronouth7303** [ppb/pursuedpybear#377]
PyGame has been broken on Python 3.8 since 3.8 started its release process (we removed 3.8 support [9mo ago](https://github.com/ppb/pursuedpybear/commit/3eb44f333279b0a49655adf82ba48f532feb90a8)). The PyGame project has no plans to fix this:

[PPB](https://twitter.com/pursuedpybear/status/1229454583610716160):
> Hey @pygame_org! Any chance of a Py3.8-compatible release? This has become a serious problem for us.

[PyGame](https://twitter.com/pygame_org/status/1229822479515955201):
> No.

The background is that PyGame has abandoned any PyGame 1 development or maintenance and is devoting all of their effort to PyGame 2. However, there is currently no indications if or when PyGame 2 will have a release of any kind.

PyGame is causing us to break our own support goals (always the latest Python, tracking the PSF's own support timelines), and they have no plans to fix this.

This is untennable for PPB, so we must consider our options.

1. Get PyGame to fix it (This would require extraordinary measures)
2. Fix PyGame for them (we'd be investing in an external project for an indeterminate amount of time to limp it along until its actual maintainers decides to do their job)
3. Change PPB's backend engine (proven extremely doable by the [pyglet spike](https://github.com/ppb/pursuedpybear/pull/169), there's just no slam-dunk backends available)

My assessment is that Option 3 will get us the most long-term value. Before discussing possible backends, a quick run through criteria:

* Stable on Linux, Windows, and Mac
* Supports Python versions roughly following PSF's Python lifetime schedules
* Installable through the Python ecosystem with no additional steps
* Must not compromise our own goals (eg, force us to apologize about gotchas)

The backend options we're aware of are:
* Pyglet: A pure-python system with its own platform code for Windows, Mac, and Linux/X11
* Thin SDL bindings: There are several projects in this category, some are C, some are ctypes
* Write our own platform code: While this is technically an option, none of us want to do it and we lack expertise to execute on 3-platform support

Pyglet's major problem is that there are crashing bugs on mac. (https://github.com/pyglet/pyglet/issues/5 https://bitbucket.org/pyglet/pyglet/issues/199/attempting-to-resize-or-close-pyglet https://bitbucket.org/pyglet/pyglet/issues/229/closing-window-causes-a-crash-on-mac-os) However, I would guess that after these problems are fixed, we would need to invest little-to-none in Pyglet for it to continue to work.

The SDL bindings currently have primarily shipping problems--they don't ship 3 platforms of binary wheels with SDL bundled. This is something that can be fixed with the application of CI/CD. We may even find it beneficial to adopt or fork one of the projects. I expect on-going upkeep to be low, just keeping up with CPython and SDL releases.

What direction we go in is a high-level strategic decision.

**Comment by astronouth7303** [comment]
For the record, I think if I were to redo the pyglet version, I would probably copy the `pyglet.sprite` module and adapt it to our existing data model, rather than what I did in the spike (update the pyglet data model from our own).

**Comment by astronouth7303** [comment]
PyGame update: "The longer answer than No is that there are releases for python 3.8 already." I believe these are the PyGame 2 dev releases on PyPI.

Neither Piper nor I consider inconsistent pre-alpha dev snapshots to be suitable for our target audience.

**Comment by pvcraven** [comment]
In addition to Pyglet, you might want to look at the Arcade Sprite and SpriteList implementations for ideas. It's open-source and you can freely steal from it.

https://arcade.academy/

**Comment by pvcraven** [comment]
The auto-creation of hitboxes and batch drawing of sprites are nice features.

**Comment by astronouth7303** [comment]
@pvcraven https://github.com/pvcraven/arcade/blob/master/arcade/sprite.py and https://github.com/pvcraven/arcade/blob/master/arcade/sprite_list.py? I love prior art and not having to write shaders myself! Thank you.

**Comment by pvcraven** [comment]
Sure. I'm particularly happy with creating a hitbox around the sprite by looking at the transparent pixels.

You can draw a million stationary sprites by drawing them in batch, so that's pretty nice as well.

**Comment by astronouth7303** [comment]
The two major SDL bindings libraries are [PySDL2](https://pypi.org/project/PySDL2/) and [pysdl2-cffi](https://pypi.org/project/pysdl2-cffi/).

PySDL2 is ctypes-based, but has the companion package [pysdl2-dll](https://pypi.org/project/pysdl2-dll/) to ship SDL binaries for Mac and Windows. Other than the lack of Linux binaries, at first glance it looks like they're on top of things and have their stuff together.

pysdl2-cffi hasn't had a release since 2015, and was only shipping wheels for Windows.

**Comment by astronouth7303** [comment]
For completeness, some other suggestions:

* [SFML](https://www.sfml-dev.org/): Looks pretty minimal, but the Python bindings look only kinda-sorta active. We'd have to effectively adopt the project.
* [LÖVE](https://love2d.org/): While the engine itself is lua-based, it is "pretty nicely split into 'parts that are generic' and 'parts that are lua wrappers'." However, a cursory search does not show any existing bindings for Python. So we would have to do all the work of separating the two and integrating the generic parts to Python.

Compared to the above solutions (which are more-or-less ready for use), neither of these present compelling cases without a referral saying that they are above-and-beyond the competition in performance and quality.

**Comment by astronouth7303** [comment]
ok, so where we're at:

* Pyglet: Ultimately more performant and featureful (we were considering moving to it for this reason anyway), but has a crashing bug on mac that we'd have to convince someone else to fix.
* PySDL: More compatible with what we're doing (hopefully), but still constrained by SDL. We'd eventually have to step into pysdl2-dll to get linux shipping. (I am perfectly capable of re-writing its CI/CD on Cirrus for 3-platform support, assuming @a-hurst is ok with that sort of contribution.) But I'm also totally ok having Linux install extra packages initially.

For just initial investment, I think PySDL wins. But if we think SDL is going to hamper us in the long-term, should we just go with Pyglet now?

Some more esoteric and distant features:

* zipapp: A distribution method for single-file apps (and I'm low-key working on tooling around this, like pyz-dispenser). pyglet is totally compatible with this, no problem. PySDL (and anything else with native components) is more complicated (granted, tools like shiv and pants should handle this).
* pypy performance: While both should run on pypy, I *speculate* that pyglet will perform better because it avoids the slow CAPI compatibility layer.
* Web: Something that would be really cool for distribution is running games on the web. The closest we get to this is repl.it's support of PyGame. Any path forward on this would likely require significant JS, WASM, and Python work.

All of these features are fairly fringe right now. They're pretty nice value-adds (especially the web option), but none of them are deal breakers or makers.

@pathunstrom what's your take?

**Comment by pathunstrom** [comment]
I'm leaning towards PySDL2 myself. Specifically because it's mostly knowns for any draw backs, I'm already familiar with using it directly, and the draw backs don't change.

But on the esoteric thoughts:

Zipapp is definitely a bridge to cross when we get there. Definitely going to be important when we have the tooling, but until then, we just need to be able to keep working.

I've got no opinion on pypy as a target runtime at this moment.

Web is one I've been thinking about and I currently think it's a case where us building JS client code is the correct long term solution, with an optional feature to run ppb in a web server. Inn general, web delivery is just. . . a huge undertaking that I'm not sure is constrained by choice of library on the server side.

**Comment by astronouth7303** [comment]
Yeah, my current thought on web is CPython on WASM, JS wasm-canvas connector, and new PPB backend. Makes hosting a static affair, so people can throw them wherever with minimal operational concerns.

Sounds like for us PySDL is the way to go for now? The drawbacks are that the SDL render model don't make it clear if/how we can do real batch rendering, and the sound engine is inferior to the pyglet one. (Pyglet supporting full spacial sound, whereas SDL supports just a simple stereo mixer.)

**Comment by astronouth7303** [comment]
Correction: SDL does support some form of batch rendering, but it's not super-obvious how this works. Piper will be digging into it more.

**Comment by pathunstrom** [comment]
Finally did enough digging to land on some firm stuff on the SDL batch rendering.

Here's the most important thread from the SDL forums: https://discourse.libsdl.org/t/a-couple-of-questions-regarding-batching-in-sdl-2-0-10/26453

Important quotes from Ryan (icculus):

> It only flushes when forced to. Specifically, in 2.0.10:
> 
> When you call SDL_RenderPresent(), it flushes because it needs to get pixels to the screen.
> When you call SDL_SetRenderTarget(), if flushes because it needs to get pixels to the current render target before we start using a new one.
> When you call SDL_RenderReadPixels(), because we need it to have the right pixels rendered before we read them. :slight_smile:
> When you Update/Lock/Bind/Unbind/Destroy a texture that’s been used by the renderer since the last flush, so we get the right texture data when drawing with stuff that’s been batched up.
> When you call SDL_RenderGetMetal*, so things are in sync.
> When you call SDL_RenderFlush(), because you’re telling it that you have to flush right now. Don’t call this unless you plan to use the underlying API directly and need things to be in sync (like if you plan to use the render API forced to OpenGL and also call OpenGL directly on that same rendering context).
> The idea with batching, though, is that it should generally work like it always has, just faster. Specifically:

and 

> assuming those SDL_Textures haven’t changed in some way between SDL render calls.
> 
> That being said, when flushing does happen, it benefits from using the same texture twice in a row, as SDL is now smart enough to only bind the texture once (in GL, Direct3D, etc) and draw from it multiple times, so you’ll see performance increases in this scenario beyond the higher-level “flushing” that SDL does.

So it sounds like in general, as long as we keep the textures around and don't mess with them (this is most of what we do) we should see performance gains effectively for free due to batching.

Still need to answer if we can get a vsync signal from SDL. Will be my next puzzle.

**Comment by pathunstrom** [comment]
Additionally, we can get additional gains by converting loaded assets into a texture atlas: https://discourse.libsdl.org/t/sdl2-sprite-batching-confusion/27148/2

**Comment by a-hurst** [comment]
Hi @astronouth7303, only just got the email for your notification now! Would be very happy with any help you're willing to provide with getting manylinux wheels for pysdl2-dll working I've already dug into it myself a bit: I have a Python script that builds SDL2 + all supported addon libraries along with their dependencies under Linux, but encountered some odd problems getting WebP to build nicely (SDL2_image dependency) and let it fall by the wayside. I can share what I have already so you're not starting from scratch. You might also want to check out the manylinux build scripts from the PyGame 2.0 team, which could be adapted/extended for the purpose of PySDL2 wheels.

As for the drawbacks of SDL2 you mentioned:

* For my own projects, I bypass SDL2's renderer completely and just use PyOpenGL with an SDL2-created window for drawing stuff to the screen. PyOpenGL can render anything that's passed to it as a properly-formatted Numpy array, so you can generate textures from pretty much any source. It should also be very similar to Pyglet in terms of the rendering backend, so that might be a solution to your problem.

* Regarding directional sound, SDL2_mixer (which PySDL2 also binds and pysdl2-dll includes) adds support for this on top of base SDL2. It also adds support for loading and playing .mp3, .ogg, FLAC, and MIDI music & sound effects (among other formats), which might be handy for a project like this. The API isn't great to work with, though.

**Comment by astronouth7303** [comment]
Yeah, when I get some time on my plate, I can look into fixing up the Linux build. I've got a lot of stuff going on, and tbh having Linux install extra packages is a reasonable compromise.

Thanks for the tip on SDL_mixer! Even if we don't end up implementing spatial sound right away (and it should be pretty easy), just having additional codec support (beyond "mp3 maybe, ogg probably") would be fantastic. Plus not having to juggle our own channels is nice.

The vsync question is mostly "Can we get hints from the underlying engine about when to start drawing frames?" We currently run frames on a constant clock (although it's documented to be irregular), but if we could do something more hardware-informed, i think that would be better?

**Comment by astronouth7303** [comment]
The only vsync I'm seeing is that we can have `SDL_RenderPresent()` block for the vertical reset, which is ... meh.
