### ISSUE TITLE
Remove pos argument from the BaseSprite.__init__

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#522]
We kept it for legacy reasons, but we've reached the point where it's just kind of an ugly appendage instead of helpful. We need to keep the type coercion in the setup function, but we can remove the error handling and check for pos entirely.

**Comment by Gideon357** [comment]
I'd be interested in taking this on, is this for ppb.readthedocs.io or ppb.dev?

**Comment by pathunstrom** [comment]
It's a parameter in the code:

https://github.com/ppb/pursuedpybear/blob/canon/ppb/sprites.py#L57

You'll need to remove it there, this code block becomes dead: https://github.com/ppb/pursuedpybear/blob/canon/ppb/sprites.py#L82-L86

Remove those references and dead code and you're good.

As for those two sites: ppb.dev has its own repo (over at https://github.com/ppb/ppb.dev) and ppb.readthedocs.io uses the docs folder in this repo. I don't see a reference to the pos argument in the docs, so you won't need to do anything there.

**Comment by Gideon357** [comment]
Ops, that was stupid. I commented on the wrong issue! I meant to comment on an issue about updating the docs homepage. I feel stupid.

**Comment by reginareynolds** [comment]
Hey, I'm taking a look at the code for this right now. If we take out the pos=None and lines 82-86, is the type coercion for position still necessary? Can't that come out, too?

**Comment by AstraLuma** [comment]
They do different things. The type coercion makes sure that `.position` is a true Vector and not just vectorish. This helps UX because you know you can do any Vector operations on it, instead of hoping it's a Vector.

It should come out when we have a broader discussion about type coercion in PPB (it gives me pause because not much in Python does it) and have a more unified approach to it.

**Comment by pathunstrom** [comment]
Closed via #543
