### ISSUE TITLE
Clogs the CPU cores

### ISSUE THREAD

**Issue by js-denton** [ppb/pursuedpybear#525]
Hello. I complete tutorial from docs (https://ppb.readthedocs.io/en/stable/getting-started.html#getting-started).
All work, but i have problem with prefomance. When i run app, passes through alternately clogs cores CPU on 100%.

How to optimize?

OS: Fedora 32
CPU: intel i5-1035G1

**Comment by AstraLuma** [comment]
Yes, this is factually correct. This is due to the core event loop being a busy polling loop.

There is a yield (`sleep(0)`) in there, so the OS scheduler should be given a chance to process anything else on the system.

It should also only be one core at a time--PPB is mostly single-threaded. (With the exception of some secondary threads to do asset loading.)

The fix would be to add timer awareness to the core loop. However, that would require rejiggering a lot of stuff. At this time, this is low priority work because:

* Games generally monopolize users attention, reducing the need to play nice with others in this regard
* Other game engines (notably Love2D) also do this
* It's going to add a bunch of complexity to the core event loop and core systems

Things like [txpursuedpybear](https://github.com/ppb/txpursuedpybear) will improve on this because they use a fix polling clock instead of a busy loop. But that has potential latency trade-offs.

**Comment by js-denton** [comment]
OK, thanks for the detailed answer
