### ISSUE TITLE
Question: how to create rectangular sprites?

### ISSUE THREAD

**Issue by refaelsh** [ppb/pursuedpybear#565]
Hi all,

Question: how to create rectangular sprites? Where is it in the docs? Or even better, are there any code samples?

Thanks. All.

**Comment by pathunstrom** [comment]
API documentation is here:

https://ppb.readthedocs.io/en/stable/reference/sprites.html#ppb.RectangleSprite

The only catch is you'll want the aspect ratio of the sprite to match the images you use.

The big difference between `RectangleSprite` and `Sprite` is that `Sprite` uses `size` and `RectangleSprite` only has `height` and `width`.

Going to close this because there isn't ppb work associated with it, consider joining our discord and ask in the #making-games channel for further questions of this type. https://discord.gg/BwxQgYE9X2

**Comment by refaelsh** [comment]
I understand. Thank you. I am still having troubles after reading the docs. I will ask in Discord as you requested. Again, thank you.
