### ISSUE TITLE
Broken link in asset system reference

### ISSUE THREAD

**Issue by pathunstrom** [ppb/pursuedpybear#607]
The reference to ppb.assets.Circle on https://ppb.readthedocs.io/en/stable/discussion/assets.html is not hyperlinkers properly.

This should probably reference Ellipse instead, but we also want the hyperlink to be generated.

**Comment by pathunstrom** [comment]
Same page AssetLoadingSystem is also not hyperlinked properly.

**Comment by pathunstrom** [comment]
Asset.free() is another one.

**Comment by pathunstrom** [comment]
The final `load` reference is broken as well.

**Comment by tran-dy** [comment]
Hi, I took a stab at correcting some of the links on this doc page.

Wasn't positive on how to proceed to correct for the AssetLoadingSystem reference since there didn't seem to be a section for that in the docs already.

Would that fit in as a section right before "General Asset Interface" section on this page ([https://ppb.readthedocs.io/en/stable/reference/assets.html](https://ppb.readthedocs.io/en/stable/reference/assets.html))?

**Comment by ProsperousHeart** [comment]
Has this been completed?

**Comment by AstraLuma** [comment]
Looks like!
